### ISSUE TITLE
Could not load StaffChat.jar on startup.

### ISSUE THREAD

**Issue by magrrtt** [JavaGuy12/StaffChat#1]
[Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.itguy12.staffchat.main
 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.itguy12.staffchat.main'
 [Server] ERROR Could not load 'plugins/StaffChat.jar' in folder 'plugins'

**Comment by jacksoneshbaugh** [comment]
Hello! I have fixed this error, try re-downloading the latest version!

Thanks!
